### ISSUE TITLE
Foreign keys of type MtVarchar create duplicate column declarations.

### ISSUE THREAD

**Issue by jjzazuet** [vaccovecrana/metolithe#31]
Example:

```java
@MtEntity
public class GkProxy {
  @MtPk
  public int pid;

  @MtFk(GkProxyGroup.class)
  @MtUnique(idx = 0, inPk = true)
  public int gid;

  @MtIndex
  @MtFk(GkRegion.class)
  @MtVarchar(64) @MtNotNull
  public String regionCode;

  @MtVarchar(32) @MtIndex
  @MtFk(GkApiToken.class)
  public String tkId;
}
```

Changeset:

```yaml
- changeSet:
    id: tbl_gkproxy
    author: generated
    changes:
    - createTable:
        tableName: gkproxy
        columns:
        - column:
            name: pid
            type: int
            constraints: {nullable: 'false', primaryKey: 'true'}
- changeSet:
    id: tbl_col_gkproxy_gid
    author: generated
    changes:
    - addColumn:
        tableName: gkproxy
        columns:
        - column: {name: gid, type: int}
- changeSet:
    id: tbl_col_gkproxy_regioncode
    author: generated
    changes:
    - addColumn:
        tableName: gkproxy
        columns:
        - column:
            name: regioncode
            type: varchar(64)
            constraints: {nullable: 'false'}
- changeSet:
    id: tbl_col_gkproxy_tkid
    author: generated
    changes:
    - addColumn:
        tableName: gkproxy
        columns:
        - column: {name: tkid, type: varchar(32)}
- changeSet:
    id: tbl_col_gkproxy_regioncode
    author: generated
    changes:
    - addColumn:
        tableName: gkproxy
        columns:
        - column:
            name: regioncode
            type: varchar(64)
            constraints: {nullable: 'false'}
- changeSet:
    id: tbl_col_gkproxy_tkid
    author: generated
    changes:
    - addColumn:
        tableName: gkproxy
        columns:
        - column: {name: tkid, type: varchar(32)}
- changeSet:
    id: idx_gkproxy_regioncode
    author: generated
    changes:
    - createIndex:
        indexName: idx_gkproxy_regioncode
        tableName: gkproxy
        columns:
        - column: {name: regioncode}
- changeSet:
    id: idx_gkproxy_tkid
    author: generated
    changes:
    - createIndex:
        indexName: idx_gkproxy_tkid
        tableName: gkproxy
        columns:
        - column: {name: tkid}
- changeSet:
    id: fk_50ca2627
    author: generated
    changes:
    - addForeignKeyConstraint: {baseColumnNames: gid, baseTableName: gkproxy, constraintName: fk_50ca2627,
        referencedColumnNames: gid, referencedTableName: gkproxygroup}
- changeSet:
    id: fk_78c6e4cf
    author: generated
    changes:
    - addForeignKeyConstraint: {baseColumnNames: regioncode, baseTableName: gkproxy,
        constraintName: fk_78c6e4cf, referencedColumnNames: regioncode, referencedTableName: gkregion}
- changeSet:
    id: fk_9f093101
    author: generated
    changes:
    - addForeignKeyConstraint: {baseColumnNames: tkid, baseTableName: gkproxy, constraintName: fk_9f093101,
        referencedColumnNames: tkid, referencedTableName: gkapitoken}
```
